"""add body_html

Revision ID: 36b625d19fcc
Revises: 21016b22f984
Create Date: 2015-07-24 16:53:23.781000

"""

# revision identifiers, used by Alembic.
revision = '36b625d19fcc'
down_revision = '21016b22f984'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
