"""empty message

Revision ID: 3ce3e13c0f2c
Revises: None
Create Date: 2015-07-08 11:26:42.465000

"""

# revision identifiers, used by Alembic.
revision = '3ce3e13c0f2c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
